### ISSUE TITLE
オリジナルツイート(リプライされた方) を取得する際の例外処理が実装されていない

### ISSUE THREAD

**Issue by mori97** [mori97/KaiRA-ChatBot#1]
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 83, in create_connection
    raise err
  File "/usr/lib/python3.6/site-packages/urllib3/util/connection.py", line 73, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 601, in urlopen
    chunked=chunked)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 346, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 850, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 284, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.6/site-packages/urllib3/connection.py", line 146, in _new_conn
    (self.host, self.timeout))
urllib3.exceptions.ConnectTimeoutError: (<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff9cc5773c8>, 'Connection to api.twitter.com timed out. (connect timeout=60)')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/usr/lib/python3.6/site-packages/urllib3/connectionpool.py", line 639, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/lib/python3.6/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/show.json?id=942007622617645056 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff9cc5773c8>, 'Connection to api.twitter.com timed out. (connect timeout=60)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/tweepy/binder.py", line 187, in execute
    proxies=self.api.proxy)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.6/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.6/site-packages/requests/adapters.py", line 496, in send
    raise ConnectTimeout(e, request=request)
requests.exceptions.ConnectTimeout: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/show.json?id=942007622617645056 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff9cc5773c8>, 'Connection to api.twitter.com timed out. (connect timeout=60)'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "mining.py", line 109, in <module>
    main()
  File "mining.py", line 93, in main
    stream.userstream()
  File "/usr/lib/python3.6/site-packages/tweepy/streaming.py", line 394, in userstream
    self._start(async)
  File "/usr/lib/python3.6/site-packages/tweepy/streaming.py", line 361, in _start
    self._run()
  File "/usr/lib/python3.6/site-packages/tweepy/streaming.py", line 294, in _run
    raise exception
  File "/usr/lib/python3.6/site-packages/tweepy/streaming.py", line 263, in _run
    self._read_loop(resp)
  File "/usr/lib/python3.6/site-packages/tweepy/streaming.py", line 324, in _read_loop
    self._data(next_status_obj)
  File "/usr/lib/python3.6/site-packages/tweepy/streaming.py", line 297, in _data
    if self.listener.on_data(data) is False:
  File "/usr/lib/python3.6/site-packages/tweepy/streaming.py", line 54, in on_data
    if self.on_status(status) is False:
  File "mining.py", line 36, in on_status
    tweet['in_reply_to_status_id'])._json
  File "/usr/lib/python3.6/site-packages/tweepy/binder.py", line 245, in _call
    return method.execute()
  File "/usr/lib/python3.6/site-packages/tweepy/binder.py", line 189, in execute
    raise TweepError('Failed to send request: %s' % e)
tweepy.error.TweepError: Failed to send request: HTTPSConnectionPool(host='api.twitter.com', port=443): Max retries exceeded with url: /1.1/statuses/show.json?id=942007622617645056 (Caused by ConnectTimeoutError(<urllib3.connection.VerifiedHTTPSConnection object at 0x7ff9cc5773c8>, 'Connection to api.twitter.com timed out. (connect timeout=60)'))

**Comment by mori97** [comment]
リトライデコレータを作れば解決できる？
要調査
